.gitignore, Cargo.toml, examples/mouse_picking.rs, src/debug.rs, src/lib.rs, src/primitives.rs, src/raycast.rs
I removed the parallel iteration because of the removal of `par_iter()`. It being replaced with `.par_for_each()` and `.par_for_each_mut()` means that we have no mechanism for aggregating results outside of a concurrent container. Using an `Arc<Mutex<Vec>>` might work, and I quickly tried it, but the example stopped functioning and I didn't debug further. I'm not sure if the cost of a Mutex outweighs the cost of not parallelizing here.
The change of note is glam's moving of `transform_point3()` to `project_point3()` and replacing it with a function that does the same thing sans multiplication by the projection matrix.
=> Update master to track Bevy main

src/primitives.rs
`to_transform` name implies it takes ownership
It's used only once and it can take it in this case
=> fix clippy lint

Cargo.toml, benches/ray_mesh_intersection.rs, src/lib.rs
This PR makes `ray_mesh_intersection` public and adds benchmarks on it
My computer is very not good for running benchmarks, but I get those results:
```
ray_mesh_intersection/100_vertices
time:   [3.5276 us 3.5889 us 3.6599 us]
Found 4 outliers among 100 measurements (4.00%)
3 (3.00%) high mild
1 (1.00%) high severe
ray_mesh_intersection/10000_vertices
time:   [417.07 us 426.85 us 439.25 us]
Found 8 outliers among 100 measurements (8.00%)
2 (2.00%) low mild
2 (2.00%) high mild
4 (4.00%) high severe
ray_mesh_intersection/1000000_vertices
time:   [44.719 ms 45.009 ms 45.327 ms]
Found 5 outliers among 100 measurements (5.00%)
2 (2.00%) high mild
3 (3.00%) high severe
ray_mesh_intersection_no_intersection/100_vertices
time:   [3.3899 us 3.4160 us 3.4398 us]
Found 1 outliers among 100 …
```
=> adding benchmarks on `ray_mesh_intersection`

src/lib.rs, src/raycast.rs
Building on #17, this should bring some optimisations
```
ray_mesh_intersection/100_vertices
time:   [2.5537 us 2.5698 us 2.5862 us]
Found 1 outliers among 100 measurements (1.00%)
1 (1.00%) high severe
ray_mesh_intersection/10000_vertices
time:   [302.76 us 304.54 us 306.30 us]
Found 5 outliers among 100 measurements (5.00%)
2 (2.00%) high mild
3 (3.00%) high severe
ray_mesh_intersection/1000000_vertices
time:   [35.273 ms 35.525 ms 35.841 ms]
Found 3 outliers among 100 measurements (3.00%)
1 (1.00%) low mild
1 (1.00%) high mild
1 (1.00%) high severe
ray_mesh_intersection_no_intersection/100_vertices
time:   [2.4214 us 2.4359 us 2.4505 us]
Found 5 outliers among 100 measurements (5.00%)
3 (3.00%) high mild
2 (2.00%) high severe
ray_mesh_intersection_no_intersection/10000_vertices
time: …
```
=> Optimisations on `triangle_intersection`

examples/ray_intersection_over_mesh.rs, src/lib.rs
Having direct access to this method is useful in some cases where one need to check a varying number of rays depending on the situation.
Also added an example using it
=> add public helper `ray_intersection_over_mesh` to use directly ray casting without going through the ECS

examples/mouse_picking.rs
The issue was that for every camera, the events were iterated, meaning that on the second camera the events had already been cleared. By inverting the order, multiple screenspace raycast sources in the same set work now.
Note that multiple debug cursors don't work because the code assumes a one-to-one mapping between picking sets and debug cursors. Maybe the plugin state configuration 
```rust
pub build_rays: bool,
pub update_raycast: bool,
pub update_debug_cursor: bool,
```
could be moved to the `RayCastSource`? It seems to me like these booleans should be a property of the source, not the picking set.
=> fix multiple raycast sources with screenspace rays

Cargo.toml, README.md, examples/bounding_volume.rs, examples/mouse_picking.rs, examples/ray_intersection_over_mesh.rs, examples/simplified_mesh.rs, src/lib.rs, src/primitives.rs
The biggest change is that the camera no longer references a window directly, but instead a RenderTarget. This new class has methods that directly support getting the window size.
=> Updated to bevy 0.7

examples/bounding_volume.rs, examples/minimal.rs, examples/mouse_picking.rs, examples/ray_intersection_over_mesh.rs, examples/simplified_mesh.rs, src/debug.rs, src/lib.rs, src/primitives.rs
Updates the `Intersection` struct to actually be used as a component.
This makes it possible to query for intersections, instead of querying pick sources, and checking `intersect_top`.
=> Intersection component refactor

src/primitives.rs
After [this commit](https://github.com/bevyengine/bevy/commit/2e8dfc0) was merged to bevy/main in the Bevy repo, the Camera struct no longer has the near value stored.
This just calculates the near value from the camera's projection matrix
=> Fixed Ray3d::from_screenspace

examples/mouse_picking_2d.rs, src/lib.rs
Follow up on https://github.com/aevyrie/bevy_mod_picking/issues/7.
=> Add support for `MaterialMesh2dBundle`

src/lib.rs
Fix for changes in Bevy from commit bevyengine/bevy@c5e89894f45e694f882a0e2831af1d2452bac257 , which removed the task_pool parameter from Query::par_for_each
=> Adjust to change in signature of Query::par_for_each

Cargo.toml
This pull request narrows down the list of bevy features.
Currently, requiring `bevy_mod_cast` pulls the whole of bevy. For example, `bevy_mod_picking` also pulls the whole of bevy.
=> Only include bevy features that we need.

src/primitives.rs
Thanks for this amazing library!
In my application we follow a z-up convention instead of y-up, and I found myself getting very confused about how to make the transform line up with the rays correctly. Eventually I found that this tweak to the API is the simplest way to make everything work nicely. Best of all, it has no negative impact on API.
=> Add an API for choosing a different up direction

src/debug.rs, src/lib.rs, src/primitives.rs, src/raycast.rs
Fixes compilation when the default features are disables.
I also splitted `use` to make `cfg(feature ...)` look better. By default rust-analyzer splits includes into std, third-party and your, so I did the same.
=> Fix compilation without default features

src/lib.rs, src/primitives.rs
This PR is a suggestion to refactor the API for `RayCastSource::Intersect_primitive`.
I've found that I frequently have a need for calculating a ray's application with a plane in my application, and I thought it would be better if the `Ray3d` class had a convenience function for that. I noticed that `RayCastSource` has the right calculation, but the calculation really only needs the information of a `Ray3d`, it doesn't need all the information in a `RayCastSource`. So I've migrated the implementation from `RayCastSource` into `Ray3d` and redirected `RayCastSource`'s implementation to just use the `Ray3d` one.
This shouldn't break any API, it only expands the API.
=> Refactor intersect_primitive API

src/lib.rs
The current implementation gives wrong results for non-indexed meshes.
To verify this, remove the indices of a mesh by calling `Mesh::duplicate_vertices()`.
Without this PR, the intersection position is correct, but the intersection normal is wrong.
=> Fix ray mesh intersection for non-indexed meshes

CHANGELOG.md, Cargo.toml, examples/bounding_volume.rs, examples/minimal.rs, examples/mouse_picking.rs, examples/mouse_picking_2d.rs, examples/ray_intersection_over_mesh.rs, examples/simplified_mesh.rs, src/lib.rs, src/raycast.rs
I think everything should be working as in the previous version but I haven't used this crate myself.
=> Update to Bevy 0.10

.github/workflows/rust.yml
Basically all of the `actions-rs/*` actions are unmaintained. See <https://github.com/actions-rs/toolchain/issues/216> for more information. Due to their age they generate several warnings in CI runs, for example in https://github.com/aevyrie/bevy_mod_raycast/actions/runs/4508108830:
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, actions-rs/toolchain@v1, Swatinem/rust-cache@ce325b60658c1b38465c06cc965b79baf32c1e72, actions-rs/cargo@v1. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
To get rid of those warnings the occurrences of `actions-rs/toolchain` are replaced by [`dtolnay/rust-toolchain`](https://github.com/dtolnay/rust-toolc …
=> Replace unmaintained actions-rs/* actions in CI workflows

src/primitives.rs
I believe this:
- fixes #5,
- allows to run with `debug-glam-assert` (otherwise it would assert on `up.cross(normal).normalize()`).
Please note I'm a dunce when it comes to maths/3D but that seems simple enough.
Before: ![before](https://user-images.githubusercontent.com/3048933/230126938-c74b2795-b5bb-4a84-86f7-fcaaf8ec40da.png)
After: ![after](https://user-images.githubusercontent.com/3048933/230127028-d6a62dc8-2b1d-4544-9ae6-6f145a89dc1a.png)
=> fix to_aligned_transform for colinear up and normal vectors

src/debug.rs, src/lib.rs, src/primitives.rs
I just made it closer to what bevy does. I think technically what bevy is doing is more correct, as it has the NDC coordinates of the ray origin starting exactly at the near plane (Z=1).
I ran the `simplified_mesh` example and it's still working as expected. If you print the calculated `near` and `far` coordinates for the ray, you'll see that this change makes the ray start at the world-space near plane (Z=-0.1).
=> Make Ray3d::from_screenspace start from the near plane

Cargo.toml, examples/bounding_volume.rs, examples/minimal.rs, examples/mouse_picking.rs, examples/mouse_picking_2d.rs, examples/ray_intersection_over_mesh.rs, examples/simplified_mesh.rs, src/lib.rs, src/primitives.rs
Supersedes #78
* Migrate to new `add_systems` API
* Derive `Reflect` instead of using `impl_reflect(_from)_value`
- Replace `Reflect` type argument bound with `TypePath` (https://bevyengine.org/learn/migration-guides/0.10-0.11/#bevy-reflect-stable-type-path-v2)
* Use `camera.view_to_world()` to implement `Ray3d::from_screenspace` (previous work: #83 #76) (see https://github.com/bevyengine/bevy/pull/8306)
* Explicitly use `ReinhardLuminance` tone mapping in examples (default tone mapping now requires including LUTs)
=> Update to Bevy v0.11

Cargo.toml, examples/mouse_picking.rs, src/primitives.rs
Bevy 0.11 seems to have an undocumented change to viewport to world ray construction. This fixes that to use viewport coordinates instead of screen coordinates. Picking example updated as well.
=> Viewport fix

examples/mouse_picking.rs, examples/mouse_picking_2d.rs, examples/simplified_mesh.rs, examples/stress_test.rs, src/lib.rs, src/primitives.rs, src/system_param.rs
When working with `bevy_mod_picking` I noticed that pick events are not triggered when I work with a viewport positioned with an offset relative to the window. I tracked issue down to this package. One can reproduce the issue by running `mouse_picking` example on a high density display: the rays will not match with mouse cursor.
Turns out, the viewport offset calculation doesn't take into account pixel density of the screen. We have access to this information in `Window` though. So I make an assumption that we are working with the primary window, and pass the object down to the offset calculation.
I also borrowed helper code for `low_latency_window_plugin` from `bevy_mod_picking` while at it.
This PR fixes one of the root issues https://github.com/aevyrie/bevy_mod_raycast/pull/91 tried to …
=> Include window scale factor in viewport offset calculation

examples/mouse_picking.rs
Before these changes, the `mouse_picking` example would:
- Not print intersections
Fixed by moving the `print_intersections` method to an Update system
- Shoot a ray from an offsetted mouse position
Fixed by getting rid of the camera viewport settings
=> Fix the mouse_picking example

CHANGELOG.md, Cargo.toml, README.md
- Fixed: window scale factor not being considered for screenspace raycasts.
=> V0.14.0-release

Cargo.toml, src/deferred.rs, src/immediate.rs, src/lib.rs, src/markers.rs, src/primitives.rs, src/raycast.rs
Converted the mod to use the individual bevy crates as dependencies instead of the just the parent crate ("bevy"). Following the lead on some of other mods in this family (eventlistener, picking etc.)
=> Switch to using individual bevy crates instead of parent "bevy" crate

README.md
The link pointed to the struct before the immediate / deferred module split.
=> Fix docs.rs link to Raycast struct

src/primitives.rs, src/raycast.rs
This change exposes the intersection's barycentric coord and the triangle index so they can be used to look up vertex attributes and texcoords.
=> Expose barycentric coord and triangle index

examples/minimal.rs, examples/minimal_deferred.rs, examples/mouse_picking_deferred.rs, examples/reflecting_laser.rs, examples/simplified_mesh.rs, src/immediate.rs
Fixes the doc test in the bevy-0.13 branch to make CI green again.
=> Fix CI in bevy-0.13 branch
